import { Toaster } from "sonner";
import { Roboto } from "next/font/google";
import "./globals.css"
import Navbar from "./(main)/_components/Navbar";
import ConvexClientProvider from "../components/ConvexClientProvider";

const inter = Roboto({ subsets: ["latin"],
weight: ["300"]
});

export const metadata = {
  title: "Mr.Story",
  description: "Generated by Hojun Seo",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/icons/mr_story_logo.svg",
        href: "/icons/mr_story_logo.svg"
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/icons/mr_story_logo_dark.svg",
        href: "/icons/mr_story_logo_dark.svg"
      }
    ]
  }
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <title>Mr.Story</title>
        <meta name='theme-color' content='#25467F' />
        <link rel='manifest' href='/manifest.json' />
      </head>
      
      <body className={inter.className}>
          <ConvexClientProvider>
            <Navbar/>
            <Toaster position="bottom-center"/>
            {children}
          </ConvexClientProvider>
      </body>
      
    </html>
  );
}
