import { Toaster } from "sonner";
import Navbar from "./(main)/_components/Navbar"
import { Roboto } from "next/font/google";
import "./globals.css"

const inter = Roboto({ subsets: ["latin"],
weight: ["300"]
});

export const metadata = {
  title: "Mr.Story",
  description: "Generated by Hojun Seo",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/icons/mr_story_logo.svg",
        href: "/icons/mr_story_logo.svg"
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/icons/mr_story_logo_dark.svg",
        href: "/icons/mr_story_logo_dark.svg"
      }
    ]
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Mr.Story</title>
      </head>
      <body className={inter.className}>
          <Toaster position="bottom-center"/>
          {children}
        </body>
    </html>
  );
}
