import type { Metadata } from "next";
import { Dosis, Nanum_Gothic } from "next/font/google";
import { Toaster } from 'sonner'
import { ConvexProvider } from "@/components/providers/ConvexProvider";

import "./globals.css";

const nanumGothic = Dosis({
  style: "normal",
  weight: "400",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Mr.Story",
  description: "Generated by create next app",
  icons: {
    icon: "/src/app/favicon.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nanumGothic.className}>
        <ConvexProvider>
          <Toaster position="bottom-right"/>
          { children }
        </ConvexProvider>
      </body>
    </html>
  );
}
