import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import { Toaster } from 'sonner'
import { ConvexProvider } from "@/components/providers/ConvexProvider";

import "./globals.css";
import RecoilRootProvider from "@/components/providers/RecoilRootProvider";

const nanumGothic = Dosis({
  style: "normal",
  weight: "400",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Mr.Story",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/image/favicon_light.png",
        href: "/image/favicon_light.png"
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/image/favicon_dark.png",
        href: "/image/favicon_dark.png"
      }
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nanumGothic.className}>
        <ConvexProvider>
          <RecoilRootProvider>
            <Toaster position="bottom-right"/>
            { children }
          </RecoilRootProvider>
        </ConvexProvider>
      </body>
    </html>
  );
}
